#!/bin/bash
#
# mux: recompiles screen-256color with italics support. depends
#      on $TERMINFO being set
# find "vim disp" in tmux FAQ
# http://tmux.svn.sourceforge.net/viewvc/tmux/trunk/FAQ

s="screen-256color"

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
BLUE="${BOLD}$(tput setaf 4)"
YELLOW="${BOLD}$(tput setaf 3)"

msg() {
	printf "%s %s\n" "${BLUE}+${ALL_OFF}" "$@" >&2
}

msg2() {
	printf "%s %s!\n" "${YELLOW}!${ALL_OFF}" "$@" >&2
}

if [[ -z $TERMINFO ]]; then
	msg2 "environment variable TERMINFO not set"
	exit 1
fi

if [[ -f "$TERMINFO/${s:0:1}/$s" ]]; then
	msg2 "user local $s already exists"
	msg2 "removing existing terminfo"
	rm -rf "$TERMINFO/${s:0:1}/"
else
	msg2 "user local $s does not exist"
	mkdir --parents "$TERMINFO"
fi

msg "patching ${s}..."
infocmp "$s" | sed \
-e 's/^screen[^|]*|[^,]*,/screen-256color|screen-256color with italics support,/' \
-e 's/%?%p1%t;3%/%?%p1%t;3%/' \
-e 's/smso=[^,]*,/smso=\\E[7m,/' \
-e 's/rmso=[^,]*,/rmso=\\E[27m,/' \
-e '$s/$/ sitm=\\E[3m, ritm=\\E[23m,/' > "${TERMINFO}/${s}.terminfo"
msg "compiling new terminfo file"
tic "${TERMINFO}/${s}.terminfo" && msg "done!"
