#!/bin/bash
#
# mux --- recompile screen-256color with italics and xterm keys
#
# find "vim disp" in tmux FAQ
# http://sourceforge.net/p/tmux/tmux-code/ci/master/tree/FAQ
#
# xterm keys
# http://thread.gmane.org/gmane.comp.terminal-emulators.tmux.user/2197
# http://forums.vandyke.com/showthread.php?p=26580

declare -r s="screen-256color"
declare -r file="${TERMINFO:-$HOME/.terminfo}/$s.terminfo"
declare -r dir="${file%/*}"

# create directory
mkdir -p "$dir"

# generate new terminfo entry in $dir
tee >/dev/null <<EOF "$file"
$s|GNU Screen with 256 colors, italics, and xterm keys,
	initc@,
	kDC=\\E[3;2~, kEND=\\E[1;2F, kHOM=\\E[1;2H, kIC=\\E[2;2~,
	kLFT=\\E[1;2D, kNXT=\\E[6;2~, kPRV=\\E[5;2~, kRIT=\\E[1;2C,
	smso=\\E[7m, rmso=\\E[27m,
	sitm=\\E[3m, ritm=\\E[23m,
	sgr=\\E[0%?%p6%t;1%;%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;m%?%p9%t\\016%e\\017%;,
	use=screen-256color,
EOF

# clear old terminfo before invoking tic
[[ -f "$dir/${s:0:1}/$s" ]] && rm -f "$dir/${s:0:1}/$s"

# compile
tic "$file"
