#!/bin/bash

# vex: switch to and from external displays

## store xrandr output
xrandr="$(xrandr)"

swap() {
	xrandr --output "$1" --off --output "$2" --auto && return
	printf >&2 "vex: operation failed: %s off %s auto" "$1" "$2"
	return 1
}

toggle() {
	## store xrandr info for the display
	local display="$(grep -E "^$1" <<< "$xrandr")"
	local internal="LVDS1"

	## connected and active
	if (grep "+" <<< "$display" >/dev/null); then
		swap "$1" "$internal" && return
	fi
	## connected but not active
	if (grep " connected" <<< "$display" >/dev/null); then
		swap "$internal" "$1" && return
	fi

	## should not happen
	return 1
}

## generate list of external displays
list=($(awk '/^(HDMI|VGA)[0-9]+ connected/ {print $1}' <<< "$xrandr"))

## toggle first connected display in the list
for display in ${list[@]}; do
	toggle "$display" && break
done
